var beers = ['#9',
 '120 Minute IPA',
 '1554 Enlightened Black Ale',
 '60 Minute IPA',
 '90 Minute IPA',
 'Aecht Schlenkerla Rauchbier M\xc3\xa4rzen',
 'AleSmith IPA',
 'AleSmith Speedway Stout',
 'Allagash White',
 'Alpha King Pale Ale',
 'Anchor Liberty Ale',
 'Anchor Old Foghorn',
 'Anchor Porter',
 'Anchor Steam Beer',
 'ApriHop',
 'Arrogant Bastard Ale',
 'Ayinger Celebrator Doppelbock',
 'Bass Pale Ale',
 'Bells Expedition Stout',
 'Bells Hopslam Ale',
 'Bells Java Stout',
 'Bells Kalamazoo Stout',
 'Bells Oberon Ale',
 'Bells Special Double Cream Stout',
 'Big Bear Black Stout',
 'Black Butte Porter',
 'Blanche De Chambly',
 'Blind Pig IPA',
 'Blue Moon Belgian White',
 'Boddingtons Pub Ale',
 'Bourbon County Brand Stout',
 'Brooklyn Black Chocolate Stout',
 'Brooklyn Lager',
 'Brooklyn Monster Ale',
 'Brown Shugga',
 'Brutal Bitter Ale',
 'Bud Light',
 'Budweiser',
 'Burton Baton',
 'Cappuccino Stout',
 'Chicory Stout',
 'Chimay Grande R\xc3\xa9serve (Blue)',
 'Chimay Premi\xc3\xa8re (Red)',
 'Chimay Tripel (White)',
 'Chocolate Stout',
 'Choklat',
 'Christmas Ale',
 'Coors Light',
 'Corona Extra',
 'Creme Brulee (Imperial Milk Stout)',
 'Dales Pale Ale',
 'Damnation',
 'Dark Lord Imperial Stout',
 'Dead Guy Ale',
 'Delirium Tremens',
 'Doggie Style Classic Pale Ale',
 'Don de Dieu',
 'Double Bastard Ale',
 'Double Dog Double Pale Ale',
 'Double Simcoe IPA',
 'Dreadnaught IPA',
 'Duchesse De Bourgogne',
 'Duvel',
 'Fat Tire Amber Ale',
 'Festina P\xc3\xaache',
 'Founders Backwoods Bastard',
 'Founders Breakfast Stout',
 'Founders Centennial IPA',
 'Founders Devil Dancer',
 'Founders Dirty Bastard',
 'Founders Double Trouble',
 'Founders Imperial Stout',
 'Founders KBS (Kentucky Breakfast Stout)',
 'Founders Porter',
 'Founders Reds Rye PA',
 'Franziskaner Hefe-Weisse',
 'Fullers ESB',
 'Fullers London Porter',
 'Fullers London Pride',
 'Furious',
 'GKnight Imperial Red Ale',
 'Golden Monkey',
 'Gonzo Imperial Porter',
 'Great Lakes Blackout Stout',
 'Great Lakes Burning River Pale Ale',
 'Great Lakes Dortmunder Gold',
 'Great Lakes Edmund Fitzgerald Porter',
 'Green Flash West Coast I.P.A.',
 'Guinness Draught',
 'Guinness Extra Stout (Original)',
 'Gulden Draak (Dark Triple)',
 'Gumballhead',
 'Harpoon IPA',
 'Harvest Ale',
 'Hazelnut Brown Nectar',
 'Heavy Seas - Loose Cannon (Hop3 Ale)',
 'Heineken Lager Beer',
 'Hennepin (Farmhouse Saison)',
 'Hercules Double IPA',
 'Hibernation Ale',
 'Hobgoblin',
 'Hoegaarden Original White Ale',
 'Hop Ottin IPA',
 'Hop Rod Rye',
 'Hop Stoopid',
 'Hop Wallop',
 'HopDevil Ale',
 'Hopsickle Imperial India Pale Ale',
 'Houblon Chouffe Dobbelen IPA Tripel',
 'IPA',
 'Immort Ale',
 'Imperial IPA',
 'Imperial Stout',
 'India Pale Ale',
 'India Pale Ale (IPA)',
 'Indian Brown Ale',
 'La Fin Du Monde',
 'Lagunitas IPA',
 'Leffe Blonde',
 'Left Hand Milk Stout',
 'Leinenkugels Sunset Wheat',
 'Lindemans Framboise',
 'Long Hammer IPA',
 'Maharaja',
 'Matilda',
 'Maudite',
 'Maximus',
 'Midas Touch Golden Elixir',
 'Miller High Life',
 'Miller Lite',
 'Mocha Porter',
 'Murphys Irish Stout',
 'New Holland Dragons Milk Oak Barrel Ale',
 'Newcastle Brown Ale',
 'Northern Hemisphere Harvest Wet Hop Ale',
 'Nut Brown Ale',
 'Oak Aged Yeti Imperial Stout',
 'Oaked Arrogant Bastard Ale',
 'Oatmeal Stout',
 'Oktoberfest',
 'Old Chub - Scottish Style Ale',
 'Old Horizontal',
 'Old Rasputin Russian Imperial Stout',
 'Old Ruffian Barley Wine',
 'Old Stock Ale',
 'Ommegang (Abbey Ale)',
 'Orval Trappist Ale',
 'Pabst Blue Ribbon (PBR)',
 'Pale Ale',
 'Palo Santo Marron',
 'Paulaner Hefe-Weissbier Naturtr\xc3\xbcb',
 'Paulaner Oktoberfest-M\xc3\xa4rzen',
 'Pilsner Urquell',
 'Piraat Ale',
 'Pliny The Elder',
 'Porter',
 'Pranqster',
 'Prima Pils',
 'Pumking',
 'Punkin Ale',
 'P\xc3\xa9ch\xc3\xa9 Mortel (Imperial Stout Au Cafe)',
 'Racer 5 India Pale Ale',
 'Raging Bitch Belgian-Style IPA',
 'Raison Detre',
 'Rare Vos (Amber Ale)',
 'Red Rocket Ale',
 'Red Stripe Jamaican Lager',
 'Ruedrichs Red Seal Ale',
 'Saison Dupont',
 'Salvator Doppel Bock',
 'Samichlaus Bier',
 'Samuel Adams Black Lager',
 'Samuel Adams Boston Ale (Stock Ale)',
 'Samuel Adams Boston Lager',
 'Samuel Adams Cherry Wheat',
 'Samuel Adams Chocolate Bock',
 'Samuel Adams Cranberry Lambic',
 'Samuel Adams Cream Stout',
 'Samuel Adams Double Bock (Imperial Series)',
 'Samuel Adams Holiday Porter',
 'Samuel Adams Noble Pils',
 'Samuel Adams Octoberfest',
 'Samuel Adams Old Fezziwig Ale',
 'Samuel Adams Summer Ale',
 'Samuel Adams White Ale',
 'Samuel Adams Winter Lager',
 'Samuel Smiths Imperial Stout',
 'Samuel Smiths Nut Brown Ale',
 'Samuel Smiths Oatmeal Stout',
 'Samuel Smiths Winter Welcome Ale',
 'Samuel Smiths, The Famous Taddy Porter',
 'Santas Private Reserve Ale',
 'Schneider Aventinus',
 'Schneider Aventinus Weizen-Eisbock',
 'Sculpin India Pale Ale',
 'Shakespeare Oatmeal Stout',
 'Shiner Bock',
 'Sierra Nevada Anniversary Ale (2007-2009)',
 'Sierra Nevada Bigfoot Barleywine Style Ale',
 'Sierra Nevada Celebration Ale',
 'Sierra Nevada Kellerweis Hefeweizen',
 'Sierra Nevada Pale Ale',
 'Sierra Nevada Porter',
 'Sierra Nevada Southern Hemisphere Harvest Fresh Hop Ale',
 'Sierra Nevada Stout',
 'Sierra Nevada Summerfest Lager',
 'Sierra Nevada Torpedo Extra IPA',
 'Smuttynose IPA "Finest Kind"',
 'Smuttynose Robust Porter',
 'Snake Dog IPA',
 'Spaten Oktoberfestbier Ur-M\xc3\xa4rzen',
 'Spaten Optimator',
 'St. Bernardus Abt 12',
 'St. Bernardus Tripel',
 'Stella Artois',
 'Stone IPA (India Pale Ale)',
 'Stone Imperial Russian Stout',
 'Stone Levitation Ale',
 'Stone Pale Ale',
 'Stone Ruination IPA',
 'Stone Smoked Porter',
 'Stone Sublimely Self-Righteous Ale',
 'Storm King Stout',
 'Supplication',
 'Ten FIDY',
 'Terrapin Coffee Oatmeal Imperial Stout',
 'The Abyss',
 'Three Philosophers Belgian Style Blend (Quadrupel)',
 'Titan IPA',
 'Trappist Westvleteren 12',
 'Trappistes Rochefort 10',
 'Trappistes Rochefort 8',
 'Tripel Karmeliet',
 'Troegenator Double Bock',
 'Trois Pistoles',
 'Tr\xc3\xb6egs Hopback Amber Ale',
 'Tr\xc3\xb6egs Mad Elf',
 'Tr\xc3\xb6egs Nugget Nectar',
 'Two Hearted Ale',
 'Unearthly (Imperial India Pale Ale)',
 'Vanilla Porter',
 'Weihenstephaner Hefeweissbier',
 'Weihenstephaner Korbinian',
 'Westmalle Trappist Dubbel',
 'Westmalle Trappist Tripel',
 'World Wide Stout',
 'Yeti Imperial Stout',
 'Youngs Double Chocolate Stout',
 'Yuengling Traditional Lager',
 '\xc3\x89ph\xc3\xa9m\xc3\xa8re (Apple)']